version: '3.7'

services:

  gogs_db:
    image: mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: gogs123
      MYSQL_DATABASE: gogsdb
    volumes: 
      - ./mysql/:/var/lib/mysql

  gogs:
    image: gogs/gogs
    ports:
      - "22:22"
      - "3000:3000"
    depends_on: 
      - gogs_db
    volumes: 
      - ./gogs/:/data

  jenkins: 
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    links: 
      - gogs
    volumes: 
      - ./jenkins/:/var/jenkins_home

      
