version: '3.7'

services:

  salt-master:

    build: ./master
    container_name: salt-master
    expose:
     - "4505"
     - "4506"
    volumes:
     - "./formulas:/srv/salt"


  salt-minion:
    build: ./minion
    expose:
      - "4505"
      - "4506"
    depends_on:
      - salt-master
    links: 
      - salt-master
